steps:
  - uses: actions/checkout@v3
  - uses: nttld/setup-ndk@v1
    id: setup-ndk
    with:
      ndk-version: r21e
      add-to-path: true
  - run: ./build.sh
    env:
      ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
